import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '../styles/Main.module.css';

import Accordion from '@/components/UI/Accordion';
import CommissionStatus from '@/components/UI/CommissionStatus';
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  // TYPES
  interface CommissionDataConfig {
    statusOpen?: boolean;
    activeSlots?: number;
    totalSlots?: number;
  }

  // STATES
  const [commissionData, setCommissionData] = useState<CommissionDataConfig>({
    statusOpen: false,
    activeSlots: 0,
    totalSlots: 0,
  });

  // EFFECTS
  useEffect(() => {
    const getCommissionData = async () => {
      try {
        const res = await fetch('api/commissions');
        const data: CommissionDataConfig = await res.json();
        // console.log('response', data);
        setCommissionData(data);
        // console.log('commissionData', commissionData);
      } catch (error) {
        console.error('there was an error fetching the data', error);
      }
    };
    getCommissionData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    // console.log('commissionData', commissionData);
  }, [commissionData]);

  return (
    <>
      <Head>
        <title>Commissions</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className='h-28 w-full mt-4 outline-1 outline-red-900 relative'>
          <Image
            src={'svg/COMMISSIONS LOGO.svg'}
            alt='logo'
            fill
            // className='object-cover'
          />
        </div>
        <CommissionStatus commissionData={commissionData} />
        <Accordion />

        <div className='h-96 w-80 absolute -bottom-24 -left-24'>
          <Image
            src={'svg/ABSTRACT AMARY(5).svg'}
            alt='Amary Logo'
            fill
            // className='object-cover'
            className='object-contain'
          />
        </div>
      </main>
    </>
  );
}
